
site_name: Dobot ROS 2 Docs
nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting_started/overview.md
  - ROS 2 Interface:
      - Overview: ros2_interface/overview.md
      - Services: ros2_interface/services.md
      - Topics: ros2_interface/topics.md
  - Real Robot:
      - ROS2 Startup CLI: real_robot/ros2_startup.md
